### ISSUE TITLE
Subscribe to createEventHandler causes destruction error

### ISSUE THREAD

**Issue by jadbox** [garbles/yolk#102]
```
export default function Test ({props, createEventHandler}) {
   const bar = createEventHandler();
   bar.subscribe(x => console.log('logic here') );
  return (<form onSubmit={onSubmit}></form>);
}
```
Seems to trigger:
```
Rx.umd.js:1413 Uncaught ObjectUnsubscribedError

SafeSubscriber.__tryOrUnsub @ Rx.umd.js:1413
SafeSubscriber.next @ Rx.umd.js:1358
Subscriber._next @ Rx.umd.js:1308
Subscriber.next @ Rx.umd.js:1272
MapToSubscriber._next @ Rx.umd.js:8141
Subscriber.next @ Rx.umd.js:1272
Subject._finalNext @ Rx.umd.js:1064
Subject._next @ Rx.umd.js:1056
Subject.next @ Rx.umd.js:1013
Subject._next @ Rx.umd.js:1053
Subject.next @ Rx.umd.js:1013
```

**Comment by garbles** [comment]
PR with a failing test?

**Comment by jadbox** [comment]
Found out that it's only when you subscribe for another Rx subject:
```
// File Actions
export var MyAction = new Rx.Observable.Subject();

// File TestView
export default function Test ({props, createEventHandler}) {
   const bar = createEventHandler();
   bar.subscribe( Actions.MyAction );
  return (<form onSubmit={onSubmit}></form>);
}
```

**Comment by garbles** [comment]
It's related to Subject's having a `isUnsubscribed` property which is set to `true` when the observable they are subscribed to completes.

Example here where the exception is thrown after uncommenting the line
http://jsbin.com/qiyelorehi/1/edit?html,js,console

Example here where the exception is not thrown because the observable never completes
http://jsbin.com/zezavizawa/1/edit?html,js,console

**Comment by jadbox** [comment]
This sounds then that this bug is invalid since we shouldn't tie an external Subject to a view component stream that may have a shorter lifespan. Closing this issue for now.

**Comment by garbles** [comment]
Yea it looks like this is simply how a normal subject works in v5.
