### ISSUE TITLE
Is there a way to avoid `this`?

### ISSUE THREAD

**Issue by Lenne231** [garbles/yolk#53]
Is there a way to avoid `this` but use `createEventHandler`. There is currently no way to static type `this` in TypeScript.

**Comment by garbles** [comment]
Currently I do believe there is. By attaching `createEventHandler` to `this`, I can ensure that those even handlers are automatically cleaned up and the Rx subjects are disposed if the component is ever unmounted from the DOM. That being said, I've made some big changes since implementing this and I'm not 100% sure that memory leaks would still occur.

Is it enough to expose what `this` refers to? https://github.com/garbles/yolk/blob/master/src/YolkCompositeFunctionWrapper.js

**Comment by Lenne231** [comment]
So you would bind `createEventHandler` to `this` and pass it in as a parameter? This would also enable Arrow Functions as Yolk Components.

Regarding TypeScript: there will probably be a way to static type `this` in TypeScript in the future.
https://github.com/Microsoft/TypeScript/issues/3694

**Comment by garbles** [comment]
> So you would bind createEventHandler to this and pass it in as a parameter?

Been thinking about this a lot and wondering whether I should update components to simply inject a single object that contains all necessary params, e.g.

```js
function Component (dom) {
  const {props, children, createEventHandler} = dom

  // ...
}
```

Looking for resources on this approach if you know of any. I'll give it a bit more thought today.

**Comment by Lenne231** [comment]
What are the benefits of injecting a single object instead of using 3 parameters?

```javascript
function Component (props, children, createEventHandler) {
  // ...
}
```

Destucturing of `props` is much simpler with 3 parameters.

```javascript
const Title = ({ text }) => <h1>{text}</h1>;
```
Stateless functional components in React have multiple parameters as well. 
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html
https://github.com/reactjs/react-future/blob/master/07%20-%20Returning%20State/04%20-%20Callback%20Chaining.js

**Comment by garbles** [comment]
> What are the benefits of injecting a single object instead of using 3 parameters?

- Order of arguments doesn't matter
- If my component doesn't require props or children then I'm still forced to list them out
- If I wanted to inject more behaviour, I wouldn't have to add another argument

```js
function Component ({ createEventHandler }) {

}
```

> Destucturing of props is much simpler with 3 parameters.

This isn't really fair because one can still say

```js
const Title = ({ props: { text } }) => <h1>{text}</h1>;
```

> Stateless functional components in React have multiple parameters as well. 

You're linking to code that has not yet been implemented? [The example in the blog post you linked](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components) shows a component only consuming one argument.

**Comment by garbles** [comment]
Long story short, when if your function spec requires more than two arguments then it should probably accept an object/map/hash as its own argument.

**Comment by littlehaker** [comment]
+1 for `function component({props, children, createEventHandler}){}`

**Comment by garbles** [comment]
Will move toward `{props, children, createEventHandler}` and cut a new version in the near future. Been pretty sick this past week.

**Comment by KenPowers** [comment]
:+1: for passing a single argument. All this pure-functional goodness is making me feel warm and fuzzy on the inside. :relaxed:

**Comment by garbles** [comment]
Any comments on [THIS](https://github.com/garbles/yolk/pull/59) before I merge in?

**Comment by garbles** [comment]
Finished with #59
